FROM python:3.8.3-alpine

ARG ORG
ARG APP
ARG ENV
ARG UID
ARG GID
ARG PRODUCT
ARG BASE_DIR
ARG ORG_DIR
ARG PRODUCT_DIR

ENV MODULE="minio-local-dev-setup"
ENV ORG=$ORG
ENV APP=$APP
ENV ENV=$ENV
ENV PRODUCT=$PRODUCT
ENV BASE_DIR=$BASE_DIR
ENV ORG_DIR=$ORG_DIR


ENV APPUSR=appusr
ENV APPGRP=appgrp
ENV PS1="`date \"+%F %T\"` \u@\h  \w \n\n  "
ENV PRODUCT_DIR="/$BASE_DIR/$ORG_DIR/$PRODUCT"
ENV HOME_PRODUCT_DIR="/home/${APPUSR}${BASE_DIR}/$ORG_DIR/$PRODUCT"
ENV EDITOR="vim"

ENV TERM="xterm-256color"

VOLUME $PRODUCT_DIR

# START ::: install bins
RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
    bash binutils vim perl jq wget \
    curl zip unzip busybox-extras \
    su-exec sudo shadow net-tools \
    build-base gcc openssl-dev git \
    libmagic ttf-freefont make jq \
    python3-dev jpeg-dev zlib-dev \
    coreutils libffi-dev util-linux openssl lsof


# START :: install aws-cli
# In order to run awscliv2 on alpine we need more from glibc than musl
# https://github.com/aws/aws-cli/issues/4685#issuecomment-615872019
ENV GLIBC_VER=2.31-r0

RUN curl -sL https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub -o /etc/apk/keys/sgerrand.rsa.pub \
      && curl -sLO https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VER}/glibc-${GLIBC_VER}.apk \
      && curl -sLO https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VER}/glibc-bin-${GLIBC_VER}.apk \
      && apk add --no-cache glibc-${GLIBC_VER}.apk glibc-bin-${GLIBC_VER}.apk


RUN apk update && \
    apk upgrade && \
    apk add --no-cache aws-cli

# STOP  :: install aws-cli


# START ::: Enable host to container edit of proj code on ubuntu and mac.
RUN test -z $(getent group $GID | cut -d: -f1) || \
        groupmod -g $((GID+1000)) $(getent group $GID | cut -d: -f1)

RUN set -x ; addgroup -g "$GID" -S "$APPGRP" && \
  adduser \
  --disabled-password \
  -g "$GID" \
  -D \
  -s "/bin/bash" \
  -h "/home/$APPUSR" \
  -u "$UID" \
  -G "$APPGRP" "$APPUSR" && exit 0 ; exit 1

RUN echo "$APPUSR ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN echo "export PS1=\"$PS1\"" >> /home/$APPUSR/.bashrc

USER $APPUSR
ENV USER=$APPUSR
ENV GROUP=$APPGRP
# STOP  ::: enable host to container edit of proj code on ubuntu and mac.

# ::: adding OS APPUSER and APPGROUP
ADD --chown=$APPUSR:$APPGRP "." "$HOME_PRODUCT_DIR"


USER $APPUSR
WORKDIR $PRODUCT_DIR


# install aws-iam-authenticator
RUN echo -e "\n installing the aws-iam-authenticator - this might take even 3 minutes ... \n\n" && \
      mkdir -p /home/$APPUSR/bin/ && curl -o /home/$APPUSR/bin/aws-iam-authenticator \
      'https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/aws-iam-authenticator' && \
      sudo chmod +x /home/$APPUSR/bin/aws-iam-authenticator

ENV PATH /home/$APPUSR/bin:${PATH}

RUN $HOME_PRODUCT_DIR/run -a do_install_minio

CMD exec /bin/bash -c "${HOME_PRODUCT_DIR}/src/bash/run/docker-init-${MODULE}.sh"
